StudentRegistration/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using StudentRegistration.Data;
using StudentRegistration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentRegistration.Controllers
{
    public class CoursesController : Controller
    {
        private readonly AuthDBContext _db;

        public CoursesController(AuthDBContext db)
        {
            _db = db;
        }

        public IActionResult Create(Courses obj)
        {
            if (ModelState.IsValid)
            {
                _db.Courses.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(obj);
        }

        public IActionResult Courses()
        {
            IEnumerable<Courses> _courList = _db.Courses;
            return View(_courList);
        }
    }
}

StudentRegistration/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentRegistration.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StudentRegistration.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentRegistration/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using StudentRegistration.Data;
using StudentRegistration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentRegistration.Controllers
{
    public class StudentController : Controller
    {
        private readonly AuthDBContext _db;

        public StudentController(AuthDBContext db)
        {
            _db = db;
        }

        public IActionResult Create()
        {
            return View();
        }

        // Get student data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Student obj)
        {
            if (ModelState.IsValid)
            {
                _db.Stidents.Add(obj);
                _db.SaveChanges();

                return RedirectToAction("Create");
            }

            return View(obj);
        }

        // Display Student Data
        public IActionResult StudentDetails()
        {
            IEnumerable<Student> _stdList = _db.Stidents;
            return View(_stdList);
        }
    }
}

StudentRegistration/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/indexpage.css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <h1 class="text-primary">Admin Dashboard</h1>

            <p class="index-about-admin">
                Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
                Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
            </p>
        </div>

        <div class="row mt-4">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Student Register</h5>
                        <a asp-controller="Student" asp-action="Create" class="btn btn-primary btn-block">Register</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Course Details</h5>
                        <a asp-controller="Courses" asp-action="Courses" class="btn btn-primary btn-block">View</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Student Details</h5>
                        <a asp-controller="Student" asp-action="StudentDetails" class="btn btn-primary btn-block">View</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Add a New Course</h5>
                        <a asp-controller="Courses" asp-action="Create" class="btn btn-primary btn-block">Add</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

StudentRegistration/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
}

<h1 class="text-center">Welcome</h1>